defmodule Manillum.Repo.Migrations.AddCardEmbeddingAndDupMetadata do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :duplicate_candidate_ids, {:array, :uuid}, null: false, default: []
      add :collision_card_id, :uuid
      add :embedding, :vector, size: 1536
    end
  end

  def down do
    alter table(:cards) do
      remove :embedding
      remove :collision_card_id
      remove :duplicate_candidate_ids
    end
  end
end
