defmodule Manillum.Repo.Migrations.RelaxCardIdentityToNonDrafts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
                     name: "cards_unique_call_number_index"
                   )

    create unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
             name: "cards_unique_call_number_index",
             where: "(status != 'draft')"
           )
  end

  def down do
    drop_if_exists unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
                     name: "cards_unique_call_number_index"
                   )

    create unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
             name: "cards_unique_call_number_index"
           )
  end
end
