defmodule Manillum.Repo.Migrations.AddTagResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text, null: false
      add :normalized_name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "tags_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:tags, [:user_id, :normalized_name],
             name: "tags_unique_normalized_name_index"
           )

    create table(:card_tags, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :card_id,
          references(:cards,
            column: :id,
            name: "card_tags_card_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :tag_id,
          references(:tags,
            column: :id,
            name: "card_tags_tag_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:card_tags, [:card_id, :tag_id], name: "card_tags_unique_card_tag_index")
  end

  def down do
    drop constraint(:card_tags, "card_tags_card_id_fkey")

    drop constraint(:card_tags, "card_tags_tag_id_fkey")

    drop_if_exists unique_index(:card_tags, [:card_id, :tag_id],
                     name: "card_tags_unique_card_tag_index"
                   )

    drop table(:card_tags)

    drop constraint(:tags, "tags_user_id_fkey")

    drop_if_exists unique_index(:tags, [:user_id, :normalized_name],
                     name: "tags_unique_normalized_name_index"
                   )

    drop table(:tags)
  end
end
