defmodule Manillum.Repo.Migrations.FixCardIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
                     name: "cards_unique_segments_index"
                   )

    create unique_index(:cards, [:user_id, :drawer, :slug],
             name: "cards_unique_drawer_slug_index"
           )
  end

  def down do
    drop_if_exists unique_index(:cards, [:user_id, :drawer, :slug],
                     name: "cards_unique_drawer_slug_index"
                   )

    create unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
             name: "cards_unique_segments_index"
           )
  end
end
