defmodule Manillum.Repo.Migrations.AddPendingAutostubsToCards do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      add :pending_autostubs, {:array, :text}, null: false, default: []
    end
  end

  def down do
    alter table(:cards) do
      remove :pending_autostubs
    end
  end
end
