defmodule Manillum.Repo.Migrations.AddMentions do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:mentions, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("uuid_generate_v7()"), primary_key: true
      add :title, :text, null: false
      add :normalized_title, :text, null: false
      add :summary, :text
      add :year, :bigint, null: false
      add :month, :bigint
      add :day, :bigint
      add :mentioned_at, :utc_datetime, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "mentions_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :conversation_id,
          references(:conversations,
            column: :id,
            name: "mentions_conversation_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :message_id,
          references(:messages,
            column: :id,
            name: "mentions_message_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end

    create unique_index(:mentions, [:user_id, :conversation_id, :year, :normalized_title],
             name: "mentions_unique_per_conversation_year_title_index"
           )
  end

  def down do
    drop constraint(:mentions, "mentions_user_id_fkey")

    drop constraint(:mentions, "mentions_conversation_id_fkey")

    drop constraint(:mentions, "mentions_message_id_fkey")

    drop_if_exists unique_index(:mentions, [:user_id, :conversation_id, :year, :normalized_title],
                     name: "mentions_unique_per_conversation_year_title_index"
                   )

    drop table(:mentions)
  end
end
