defmodule Manillum.Repo.Migrations.AddLinkResource do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:links, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :kind, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :from_card_id,
          references(:cards,
            column: :id,
            name: "links_from_card_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false

      add :to_card_id,
          references(:cards,
            column: :id,
            name: "links_to_card_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          null: false
    end

    create unique_index(:links, [:from_card_id, :to_card_id, :kind],
             name: "links_unique_directed_link_index"
           )
  end

  def down do
    drop constraint(:links, "links_from_card_id_fkey")

    drop constraint(:links, "links_to_card_id_fkey")

    drop_if_exists unique_index(:links, [:from_card_id, :to_card_id, :kind],
                     name: "links_unique_directed_link_index"
                   )

    drop table(:links)
  end
end
