defmodule Manillum.Repo.Migrations.AddCallNumberRedirect do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:call_number_redirects, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :drawer, :text, null: false
      add :date_token, :text, null: false
      add :slug, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "call_number_redirects_user_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false

      add :current_card_id,
          references(:cards,
            column: :id,
            name: "call_number_redirects_current_card_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ), null: false
    end

    create unique_index(:call_number_redirects, [:user_id, :drawer, :date_token, :slug],
             name: "call_number_redirects_unique_old_call_number_index"
           )
  end

  def down do
    drop constraint(:call_number_redirects, "call_number_redirects_user_id_fkey")

    drop constraint(:call_number_redirects, "call_number_redirects_current_card_id_fkey")

    drop_if_exists unique_index(:call_number_redirects, [:user_id, :drawer, :date_token, :slug],
                     name: "call_number_redirects_unique_old_call_number_index"
                   )

    drop table(:call_number_redirects)
  end
end
