defmodule Manillum.Repo.Migrations.LinkCaptures do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:captures) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "captures_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :message_id,
             references(:messages,
               column: :id,
               name: "captures_message_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:captures, [:conversation_id])

    create index(:captures, [:message_id])
  end

  def down do
    drop_if_exists index(:captures, [:message_id])

    drop_if_exists index(:captures, [:conversation_id])

    drop constraint(:captures, "captures_conversation_id_fkey")

    drop constraint(:captures, "captures_message_id_fkey")

    alter table(:captures) do
      modify :message_id, :uuid
      modify :conversation_id, :uuid
    end
  end
end
