defmodule Manillum.Repo.Migrations.DropBlockCruft do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:messages) do
      remove :blocks
    end

    alter table(:captures) do
      remove :block_index
    end
  end

  def down do
    alter table(:captures) do
      add :block_index, :bigint
    end

    alter table(:messages) do
      add :blocks, {:array, :map}, null: false, default: []
    end
  end
end
