defmodule Manillum.Repo.Migrations.AddCaptureFullSchema do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:captures) do
      add :source_text, :text, null: false
      add :scope, :text, null: false
      add :block_index, :bigint
      add :selection_start, :bigint
      add :selection_end, :bigint
      add :status, :text, null: false, default: "pending"
      add :error_reason, :text
      add :conversation_id, :uuid
      add :message_id, :uuid

      add :user_id,
          references(:users,
            column: :id,
            name: "captures_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false
    end
  end

  def down do
    drop constraint(:captures, "captures_user_id_fkey")

    alter table(:captures) do
      remove :user_id
      remove :message_id
      remove :conversation_id
      remove :error_reason
      remove :status
      remove :selection_end
      remove :selection_start
      remove :block_index
      remove :scope
      remove :source_text
    end
  end
end
