defmodule Manillum.Repo.Migrations.AddArchiveResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:cards, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :drawer, :text, null: false
      add :date_token, :text, null: false
      add :slug, :text, null: false
      add :card_type, :text, null: false
      add :front, :text, null: false
      add :back, :text, null: false
      add :status, :text, null: false, default: "draft"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :user_id,
          references(:users,
            column: :id,
            name: "cards_user_id_fkey",
            type: :uuid,
            prefix: "public"
          ),
          null: false

      add :capture_id, :uuid
    end

    create unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
             name: "cards_unique_segments_index"
           )

    create table(:captures, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:cards) do
      modify :capture_id,
             references(:captures,
               column: :id,
               name: "cards_capture_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:captures) do
      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:captures) do
      remove :updated_at
      remove :inserted_at
    end

    drop constraint(:cards, "cards_capture_id_fkey")

    alter table(:cards) do
      modify :capture_id, :uuid
    end

    drop table(:captures)

    drop constraint(:cards, "cards_user_id_fkey")

    drop_if_exists unique_index(:cards, [:user_id, :drawer, :date_token, :slug],
                     name: "cards_unique_segments_index"
                   )

    drop table(:cards)
  end
end
