defmodule Manillum.Repo.Migrations.RelaxCaptureFkOnDeleteToNilify do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:captures, "captures_message_id_fkey")

    drop constraint(:captures, "captures_conversation_id_fkey")

    alter table(:captures) do
      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "captures_conversation_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )

      modify :message_id,
             references(:messages,
               column: :id,
               name: "captures_message_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :nilify_all
             )
    end
  end

  def down do
    drop constraint(:captures, "captures_conversation_id_fkey")

    drop constraint(:captures, "captures_message_id_fkey")

    alter table(:captures) do
      modify :message_id,
             references(:messages,
               column: :id,
               name: "captures_message_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :conversation_id,
             references(:conversations,
               column: :id,
               name: "captures_conversation_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end
  end
end
