defmodule Manillum.Repo.Migrations.AddCollisionCardRelationship do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:cards) do
      modify :collision_card_id,
             references(:cards,
               column: :id,
               name: "cards_collision_card_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    create index(:cards, [:collision_card_id])
  end

  def down do
    drop_if_exists index(:cards, [:collision_card_id])

    drop constraint(:cards, "cards_collision_card_id_fkey")

    alter table(:cards) do
      modify :collision_card_id, :uuid
    end
  end
end
